### ISSUE TITLE
Does echidna provide code coverage?

### ISSUE THREAD

**Issue by JackHFeng** [crytic/echidna#461] opened 2020-05-17 00:56 UTC
Hello, 
I was wondering, does anyone know whether echidna provides any types of code coverage after a contract is fuzzed?

**Comment by ggrieco-tob** [comment] 2020-05-17 12:57
We have in our roadmap a feature to offer more informative test results (e.g. which lines are executed) but it is not implemented yet.

Duplicate of #358.

**Closed by ggrieco-tob** 2020-05-17 12:57 UTC
