### ISSUE TITLE
Incorrect Corpus

### ISSUE THREAD

**Issue by DanielGelfand** [crytic/echidna#770] opened 2022-05-18 02:49 UTC
```
    | // SPDX-License-Identifier: MIT
    | 
    | pragma solidity 0.8.13;
*r  | 
    | contract TestContract {
    | 
    |     function test(uint x) public view returns (uint) {
    |         assert(x >= 0); // always true
    |         return x + 10;
    |     }
    | 
    |    
    | }
    | 

```

The corpus indicates that a revert happened on a line with no code. In the contract I am using version 0.8.13 with the Hardhat framework v2.9.3. Any thoughts on why this is happening?

**Comment by ggrieco-tob** [comment] 2022-05-24 15:50
I tested directly with solc (0.8.13) and I got this coverage:

```
*r  | pragma solidity 0.8.13;
    | contract TestContract {
*r  |        function test(uint x) public view returns (uint) {
*r  |             assert(x >= 0); // always true
*r  |             return x + 10;
    |        }
    | }
```

The first line seems to be covered for some reason, which is mostly caused by Solidity mappings so we need to investigate more to understand why it marked. Anyway, in your case you never get coverage of the any `test` line?

**Comment by DanielGelfand** [comment] 2022-05-24 20:32
Yes, it never got coverage of any `test` line. I believe this issue is caused by the `viaIR` hardhat setting being set to true. Otherwise, it does reach the `test` lines. However, it is still strange that I am seeing `*r` on a blank line even when setting `viaIR` to false.

**Comment by ggrieco-tob** [comment] 2022-05-25 07:46
We will investigate what maps exactly to that line. In the meantime, it seems we should recommend to disallow `viaIR` from hardhat/solidity, since that will generate mappings that has different formatting perhaps?

**Comment by ggrieco-tob** [comment] 2024-05-08 17:41
I'm closing since we already recommend to disable `viaIR`.

**Closed by ggrieco-tob** 2024-05-08 17:41 UTC
