### ISSUE TITLE
Import a feature like foundryup

### ISSUE THREAD

**Issue by 0xKarl98** [crytic/echidna#1005] opened 2023-04-03 08:37 UTC
### Describe the desired feature

Currently my echidna-test version is of 2.0.4 , but i want to upgrade it to 2.1.0. 

We should have a feature like foundryup to get it to latest with one command .

**Comment by ggrieco-tob** [comment] 2023-04-03 08:41
We are considering implementing it. Is there anything blocking you to use the precompiled latest binaries?

**Comment by montyly** [comment] 2023-04-03 09:15
Related: https://github.com/crytic/echidna/issues/811

**Comment by 0xKarl98** [comment] 2023-04-03 09:23
yeah i've download the latest version of echidna-test
how can i switch to it with the unix binary executable file ?

Feist Josselin ***@***.***> 于2023年4月3日周一 17:16写道：

**Comment by arcz** [comment] 2023-05-24 17:38
Duplicate of https://github.com/crytic/echidna/issues/811.

**Closed by arcz** 2023-05-24 17:38 UTC
Labels: enhancement
