### ISSUE TITLE
Bug: internal error: method type

### ISSUE THREAD

**Issue by 0xPhaze** [crytic/echidna#888] opened 2023-01-02 13:33 UTC
```solidity
contract Contract {
    function test_function(function(uint256) external value) public {
        assert(true);
    }
}
```

Running echidna on this contract returns the following.

```
echidna-test . --contract Contract --test-mode assertion --format text
Analyzing contract: [...]/src/Contract.sol:Contract
echidna-test: internal error: method type
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:340:22 in hevm-0.49.0-J2vJ1J8N27Q1k0k0eyS65Y:EVM.Solidity
```

**Comment by ggrieco-tob** [comment] 2023-01-03 11:42
Duplicate of #798

**Closed by ggrieco-tob** 2023-01-03 11:42 UTC
