### ISSUE TITLE
Improve etheno error message 

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#598] opened 2021-01-28 16:40 UTC
`echidna-test: Error parsing Etheno initialization file: Error in $: ',' or ']': not enough input`

I think most likely this means that you did not kill Etheno.  We could improve the error message here

**Comment by ggrieco-tob** [comment] 2021-01-28 16:52
Uhm, I need to check that, since it looks like an error produced by the code inside the json parser.

**Comment by 0xKarl98** [comment] 2023-02-21 03:51
it's not , i killed the etheno , 
but the error still exists

**Comment by arcz** [comment] 2023-02-21 14:41
@0xKarl98 do you have steps to reproduce the issue?

**Comment by ggrieco-tob** [comment] 2024-03-04 17:42
We will deprecate etheno, so I'm closing this one.

**Closed by ggrieco-tob** 2024-03-04 17:42 UTC
Labels: enhancement
